import Navbar from "@/components/Navbar";
import ToolItem from "@/components/ToolItem";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>ToolHub</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Navbar title="ToolHub"></Navbar>
        <div className="toolWrapper">
          <ToolItem
            toolDescription="Secure, customizable passwords on demand — local-only generation, strength feedback, one-click copy."
            toolName="Passwordgenerator"
            toolLink="/password"
            toolIconUrl="/ToolIcons/password.svg"
            toolImageUrl="/ToolHeaders/password.png"
          ></ToolItem>
          <ToolItem
            toolDescription="Instantly generate RFC 4122 UUIDs — copy-ready, offline."
            toolName="UUID Generator"
            toolLink="/uuid"
            toolIconUrl="/ToolIcons/uuid.svg"
            toolImageUrl="/ToolHeaders/uuid.png"
          ></ToolItem>
          <ToolItem
            toolDescription="Diff Checker is a fast, privacy-friendly tool to compare two texts and instantly highlight additions and deletions with word-level diffs."
            toolName="Diff Checker"
            toolLink="/diffChecker"
            toolIconUrl="/ToolIcons/diffChecker.svg"
            toolImageUrl=""
            isNew
          ></ToolItem>
          <ToolItem
            toolDescription="Merge multiple GPX files client-side—keeps POIs, tracks, routes; recalculates bounds; one click to download."
            toolName="GPX Merge"
            toolLink="/gpxmerge"
            toolIconUrl="/ToolIcons/gpxmerge.svg"
            toolImageUrl=""
            isNew
          ></ToolItem>
          <ToolItem
            toolDescription="Secure, customizable passwords on demand — local-only generation, strength feedback, one-click copy."
            toolName="PNG to PDF"
            toolLink="/pngtopdf"
            toolIconUrl="/ToolIcons/pngtopdf.svg"
            toolImageUrl="/ToolHeaders/pngtopdf.png"
            isWorkInProgress
          ></ToolItem>
        </div>
      </main>
    </>
  );
}
