import Navbar from "@/components/Navbar";
import ToolItem from "@/components/ToolItem";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>ToolHub</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Navbar title="ToolHub"></Navbar>
        <div className="toolWrapper">
          <ToolItem
            toolDescription="Secure, customizable passwords on demand — local-only generation, strength feedback, one-click copy."
            toolName="Passwordgenerator"
            toolLink="/tools/passwordgenerator"
            toolIconUrl="/ToolIcons/password.svg"
            toolImageUrl="/ToolHeaders/password.png"
            isWorkInProgress
          ></ToolItem>
          <ToolItem
            toolDescription="Secure, customizable passwords on demand — local-only generation, strength feedback, one-click copy."
            toolName="UUID Generator"
            toolLink="/tools/passwordgenerator"
            toolIconUrl="/ToolIcons/uuid.svg"
            toolImageUrl="/ToolHeaders/uuid.png"
            isWorkInProgress
          ></ToolItem>
        </div>
      </main>
    </>
  );
}
