import Navbar from "@/components/Navbar";
import Head from "next/head";

export default function Password() {
  return (
    <>
      <Head>
        <title>ToolHub UUID</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Navbar isSubPage title="UUID"></Navbar>
      </main>
    </>
  );
}
